api:
    enable: True
    host: "0.0.0.0"
    port: 6001
    debug: True
    name: "Muddy Boots"
website:
    enable: True
    host: "0.0.0.0"
    port: 6002
    debug: True
gui:
    enable: True
    theme: "tbc"